# Generated by Django 4.1.6 on 2023-02-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainProject.city'),
            preserve_default=False,
        ),
    ]
